# Base image
FROM node:22-alpine

LABEL name="Alpine Node 22 and npm 11" maintainer="elalconxvii@gmail.com"

WORKDIR /app
RUN npm install -g npm@11.0.0
COPY /frontend .
RUN npm install --force
EXPOSE 3000
CMD ["npm", "run", "start"]